### ISSUE TITLE
:VimskeyNote実行後の入力欄からEsc/C-[で抜けたい

### ISSUE THREAD

**Issue by See2et** [Allianaab2m/vimskey#18]
:VimskeyNote実行後にEscまたはC-[を押すとこんな感じのエラーを吐いてしまうのだ
可能であればそれで入力欄から抜けたいのだ
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/61668366/217759536-59142191-82a9-4c6d-8601-547990bd8b26.png">

**Comment by Allianaab2m** [comment]
原因は分かったんで，直しときます

**Comment by See2et** [comment]
あ、forkして修正してんだけど先に直してくれてたみたい
ありがとうございます！
